[package]
name = "cameleo"
version = "0.1.0"
edition = "2021"

[dependencies]
sdl3 = "0.14.36"
web-view = "0.7"
raw-window-handle = "0.5"
rusttype = "0.9"        # or latest SDL3 crate
image = "0.24"

