# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/oofybruh9/dev/cameleo

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/oofybruh9/dev/cameleo

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/oofybruh9/dev/cameleo/CMakeFiles /home/oofybruh9/dev/cameleo//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/oofybruh9/dev/cameleo/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named cameleo

# Build rule for target.
cameleo: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 cameleo
.PHONY : cameleo

# fast build rule for target.
cameleo/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cameleo.dir/build.make CMakeFiles/cameleo.dir/build
.PHONY : cameleo/fast

src/app.o: src/app.cpp.o
.PHONY : src/app.o

# target to build an object file
src/app.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cameleo.dir/build.make CMakeFiles/cameleo.dir/src/app.cpp.o
.PHONY : src/app.cpp.o

src/app.i: src/app.cpp.i
.PHONY : src/app.i

# target to preprocess a source file
src/app.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cameleo.dir/build.make CMakeFiles/cameleo.dir/src/app.cpp.i
.PHONY : src/app.cpp.i

src/app.s: src/app.cpp.s
.PHONY : src/app.s

# target to generate assembly for a file
src/app.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cameleo.dir/build.make CMakeFiles/cameleo.dir/src/app.cpp.s
.PHONY : src/app.cpp.s

src/bookmarks.o: src/bookmarks.cpp.o
.PHONY : src/bookmarks.o

# target to build an object file
src/bookmarks.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cameleo.dir/build.make CMakeFiles/cameleo.dir/src/bookmarks.cpp.o
.PHONY : src/bookmarks.cpp.o

src/bookmarks.i: src/bookmarks.cpp.i
.PHONY : src/bookmarks.i

# target to preprocess a source file
src/bookmarks.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cameleo.dir/build.make CMakeFiles/cameleo.dir/src/bookmarks.cpp.i
.PHONY : src/bookmarks.cpp.i

src/bookmarks.s: src/bookmarks.cpp.s
.PHONY : src/bookmarks.s

# target to generate assembly for a file
src/bookmarks.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cameleo.dir/build.make CMakeFiles/cameleo.dir/src/bookmarks.cpp.s
.PHONY : src/bookmarks.cpp.s

src/browser_manager.o: src/browser_manager.cpp.o
.PHONY : src/browser_manager.o

# target to build an object file
src/browser_manager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cameleo.dir/build.make CMakeFiles/cameleo.dir/src/browser_manager.cpp.o
.PHONY : src/browser_manager.cpp.o

src/browser_manager.i: src/browser_manager.cpp.i
.PHONY : src/browser_manager.i

# target to preprocess a source file
src/browser_manager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cameleo.dir/build.make CMakeFiles/cameleo.dir/src/browser_manager.cpp.i
.PHONY : src/browser_manager.cpp.i

src/browser_manager.s: src/browser_manager.cpp.s
.PHONY : src/browser_manager.s

# target to generate assembly for a file
src/browser_manager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cameleo.dir/build.make CMakeFiles/cameleo.dir/src/browser_manager.cpp.s
.PHONY : src/browser_manager.cpp.s

src/history.o: src/history.cpp.o
.PHONY : src/history.o

# target to build an object file
src/history.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cameleo.dir/build.make CMakeFiles/cameleo.dir/src/history.cpp.o
.PHONY : src/history.cpp.o

src/history.i: src/history.cpp.i
.PHONY : src/history.i

# target to preprocess a source file
src/history.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cameleo.dir/build.make CMakeFiles/cameleo.dir/src/history.cpp.i
.PHONY : src/history.cpp.i

src/history.s: src/history.cpp.s
.PHONY : src/history.s

# target to generate assembly for a file
src/history.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cameleo.dir/build.make CMakeFiles/cameleo.dir/src/history.cpp.s
.PHONY : src/history.cpp.s

src/search.o: src/search.cpp.o
.PHONY : src/search.o

# target to build an object file
src/search.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cameleo.dir/build.make CMakeFiles/cameleo.dir/src/search.cpp.o
.PHONY : src/search.cpp.o

src/search.i: src/search.cpp.i
.PHONY : src/search.i

# target to preprocess a source file
src/search.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cameleo.dir/build.make CMakeFiles/cameleo.dir/src/search.cpp.i
.PHONY : src/search.cpp.i

src/search.s: src/search.cpp.s
.PHONY : src/search.s

# target to generate assembly for a file
src/search.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cameleo.dir/build.make CMakeFiles/cameleo.dir/src/search.cpp.s
.PHONY : src/search.cpp.s

src/tab.o: src/tab.cpp.o
.PHONY : src/tab.o

# target to build an object file
src/tab.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cameleo.dir/build.make CMakeFiles/cameleo.dir/src/tab.cpp.o
.PHONY : src/tab.cpp.o

src/tab.i: src/tab.cpp.i
.PHONY : src/tab.i

# target to preprocess a source file
src/tab.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cameleo.dir/build.make CMakeFiles/cameleo.dir/src/tab.cpp.i
.PHONY : src/tab.cpp.i

src/tab.s: src/tab.cpp.s
.PHONY : src/tab.s

# target to generate assembly for a file
src/tab.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cameleo.dir/build.make CMakeFiles/cameleo.dir/src/tab.cpp.s
.PHONY : src/tab.cpp.s

src/theme.o: src/theme.cpp.o
.PHONY : src/theme.o

# target to build an object file
src/theme.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cameleo.dir/build.make CMakeFiles/cameleo.dir/src/theme.cpp.o
.PHONY : src/theme.cpp.o

src/theme.i: src/theme.cpp.i
.PHONY : src/theme.i

# target to preprocess a source file
src/theme.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cameleo.dir/build.make CMakeFiles/cameleo.dir/src/theme.cpp.i
.PHONY : src/theme.cpp.i

src/theme.s: src/theme.cpp.s
.PHONY : src/theme.s

# target to generate assembly for a file
src/theme.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cameleo.dir/build.make CMakeFiles/cameleo.dir/src/theme.cpp.s
.PHONY : src/theme.cpp.s

src/translate.o: src/translate.cpp.o
.PHONY : src/translate.o

# target to build an object file
src/translate.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cameleo.dir/build.make CMakeFiles/cameleo.dir/src/translate.cpp.o
.PHONY : src/translate.cpp.o

src/translate.i: src/translate.cpp.i
.PHONY : src/translate.i

# target to preprocess a source file
src/translate.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cameleo.dir/build.make CMakeFiles/cameleo.dir/src/translate.cpp.i
.PHONY : src/translate.cpp.i

src/translate.s: src/translate.cpp.s
.PHONY : src/translate.s

# target to generate assembly for a file
src/translate.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cameleo.dir/build.make CMakeFiles/cameleo.dir/src/translate.cpp.s
.PHONY : src/translate.cpp.s

src/ui/controls.o: src/ui/controls.cpp.o
.PHONY : src/ui/controls.o

# target to build an object file
src/ui/controls.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cameleo.dir/build.make CMakeFiles/cameleo.dir/src/ui/controls.cpp.o
.PHONY : src/ui/controls.cpp.o

src/ui/controls.i: src/ui/controls.cpp.i
.PHONY : src/ui/controls.i

# target to preprocess a source file
src/ui/controls.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cameleo.dir/build.make CMakeFiles/cameleo.dir/src/ui/controls.cpp.i
.PHONY : src/ui/controls.cpp.i

src/ui/controls.s: src/ui/controls.cpp.s
.PHONY : src/ui/controls.s

# target to generate assembly for a file
src/ui/controls.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cameleo.dir/build.make CMakeFiles/cameleo.dir/src/ui/controls.cpp.s
.PHONY : src/ui/controls.cpp.s

src/ui/layout.o: src/ui/layout.cpp.o
.PHONY : src/ui/layout.o

# target to build an object file
src/ui/layout.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cameleo.dir/build.make CMakeFiles/cameleo.dir/src/ui/layout.cpp.o
.PHONY : src/ui/layout.cpp.o

src/ui/layout.i: src/ui/layout.cpp.i
.PHONY : src/ui/layout.i

# target to preprocess a source file
src/ui/layout.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cameleo.dir/build.make CMakeFiles/cameleo.dir/src/ui/layout.cpp.i
.PHONY : src/ui/layout.cpp.i

src/ui/layout.s: src/ui/layout.cpp.s
.PHONY : src/ui/layout.s

# target to generate assembly for a file
src/ui/layout.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cameleo.dir/build.make CMakeFiles/cameleo.dir/src/ui/layout.cpp.s
.PHONY : src/ui/layout.cpp.s

src/utils/json_store.o: src/utils/json_store.cpp.o
.PHONY : src/utils/json_store.o

# target to build an object file
src/utils/json_store.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cameleo.dir/build.make CMakeFiles/cameleo.dir/src/utils/json_store.cpp.o
.PHONY : src/utils/json_store.cpp.o

src/utils/json_store.i: src/utils/json_store.cpp.i
.PHONY : src/utils/json_store.i

# target to preprocess a source file
src/utils/json_store.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cameleo.dir/build.make CMakeFiles/cameleo.dir/src/utils/json_store.cpp.i
.PHONY : src/utils/json_store.cpp.i

src/utils/json_store.s: src/utils/json_store.cpp.s
.PHONY : src/utils/json_store.s

# target to generate assembly for a file
src/utils/json_store.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cameleo.dir/build.make CMakeFiles/cameleo.dir/src/utils/json_store.cpp.s
.PHONY : src/utils/json_store.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... cameleo"
	@echo "... src/app.o"
	@echo "... src/app.i"
	@echo "... src/app.s"
	@echo "... src/bookmarks.o"
	@echo "... src/bookmarks.i"
	@echo "... src/bookmarks.s"
	@echo "... src/browser_manager.o"
	@echo "... src/browser_manager.i"
	@echo "... src/browser_manager.s"
	@echo "... src/history.o"
	@echo "... src/history.i"
	@echo "... src/history.s"
	@echo "... src/search.o"
	@echo "... src/search.i"
	@echo "... src/search.s"
	@echo "... src/tab.o"
	@echo "... src/tab.i"
	@echo "... src/tab.s"
	@echo "... src/theme.o"
	@echo "... src/theme.i"
	@echo "... src/theme.s"
	@echo "... src/translate.o"
	@echo "... src/translate.i"
	@echo "... src/translate.s"
	@echo "... src/ui/controls.o"
	@echo "... src/ui/controls.i"
	@echo "... src/ui/controls.s"
	@echo "... src/ui/layout.o"
	@echo "... src/ui/layout.i"
	@echo "... src/ui/layout.s"
	@echo "... src/utils/json_store.o"
	@echo "... src/utils/json_store.i"
	@echo "... src/utils/json_store.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

